---
- name: "Move and expand backend archive"
  ansible.builtin.unarchive:
    src: backend.tgz
    dest: /home/ubuntu/
- name: "install npm"
  shell: |
    cd /home/ubuntu/backend
    npm i
- name: "start backend in pm2"
  become: false
  command: pm2 start npm --name "udabackend" -- run start
  args:
    chdir: /home/ubuntu/backend
- name: "Pause for app to startup"
  pause:
    minutes: 5
