---
- name: "Move and expand backend archive"
  ansible.builtin.unarchive:
    src: backend.tgz
    dest: /home/ubuntu/
    owner: ubuntu
- name: "install npm and build"
  shell: |
    cd /home/ubuntu/dist
    npm i
- name: "configure pm2 service"
  become: yes
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu

- name: "start backend in pm2"
  become: false
  command: pm2 start npm --name "udabackend" -- run start
  args:
    chdir: /home/ubuntu/dist
- name: "Pause for app to startup"
  pause:
    minutes: 5
