---
- name: "Create backend directory"
  file:
    path: /home/circleci/backend
    state: directory
- name: "Copy backend files"
  copy:
    src: /home/circleci/project/backend
    dest: /home/circleci/backend
- name: "Start backend in pm2"
  shell: |
    cd /home/circleci/backend
    pm2 start npm -- run start
