---
- name: "Move and expand backend archive"
  ansible.builtin.unarchive:
    src: backend.tgz
    dest: /home/ubuntu/
- name: "Start backend in pm2"
  shell: |
    become: no
    cd /home/ubuntu/backend
    pm2 start npm --name "udabackend" -- start
- name: "Pause for app to startup"
  pause:
    minutes: 3
