---
  - name: Upgrade packages
    apt:
      name: "*"
      update_cache: yes
      upgrade: yes

  - name: Install dependencies
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes

  - name: Install pm2
    npm:
      name: pm2
      global: yes
      production: yes
      state: present
