---
- name: Upgrade packages
  apt:
    name: "*"
    state: latest

- name: Install dependencies
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: Install pm2
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
